apiVersion: apps/v1

kind: Deployment

metadata:
  name: mongo-app-deployment
  labels:
    app: smartbid-app

spec:
  replicas: 3

  selector:
    macthLabels:
      app: smartbid-app

  template:
    metadata:
      name: mongo-app-pod
      labels:
        app: smartbid-app
    spec:
      containers:
        - name: mongo-container
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: "BiddrProd09032020"
            - name: MONGO_INITDB_ROOT_USERNAM
              value: "smartbid"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "SmartBid1!"
