apiVersion: apps/v1

kind: Deployment

metadata:
  name: node-app-deployment
  labels:
    app: smartbid-app

spec:
  replicas: 3

  selector:
    matchLabels:
      app: smartbid-app

  template:
    metadata:
      name: node-app-pod
      labels:
        app: smartbid-app
    spec:
      containers:
        - name: node-container
          image: kbelavanaki/smartbid_node:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: MONGO_URI
              value: "mongodb+srv://smartbid:SmartBid1!@cluster0-ofksl.mongodb.net/test?retryWrites=true&w=majority"

